---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

steps:
- name: tests
  pull: default
  image: golang:1.10.2
  commands:
  - make test
  when:
    event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: gobuild
  image: golang:1.10.2
  commands:
  - make static
  - sleep 30
  environment:
    MY_FAKE_SECRET:
      from_secret: my_fake_secret
  when:
    event:
    - pull_request
    - push
    - tag

- name: build
  pull: default
  image: docker:17.09.0-ce
  commands:
  - docker build -t build .
  environment:
    DOCKER_HOST: tcp://docker:2375
  when:
    event:
    - push
    - tag

services:
- name: docker
  image: docker:18.04.0-dind
  pull: default
  ports:
  - 2375
