kind: pipeline
type: kubernetes
name: default

workspace:
  path: /go/src/github.com/UKHomeOffice/policy-admission

resources:
  request:
    cpu: 2
    memory: 8GiB
  limit:
    cpu: 4
    memory: 10GiB

steps:
- name: deps
  image: golang:1.10.2
  commands:
  - make deps

- name: test
  image: golang:1.10.2
  commands:
  - make test

- name: build
  image: golang:1.10.2
  commands:
  - make static

- name: package
  image: docker:dind
  commands:
  - docker build -t build .
  when:
    event:
    - push
    - tag
    - deployment
  volumes:
  - name: dockersock
    path: /var/run

- name: publish
  image: plugins/ecr
  environment:
    AWS_REGION: eu-west-2
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    repo: acp/policy-admission-ci
    registry: 670930646103.dkr.ecr.eu-west-2.amazonaws.com
    tags:
    - test-delete-me
  when:
    event:
    - push
    - tag
    - deployment

services:
- name: docker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}