---
kind: pipeline
name: deps

workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

steps:
- name: tests
  pull: default
  image: golang:1.10.2
  commands:
  - make deps
  when:
    event:
    - pull_request
    - push
    - tag

---
kind: pipeline
name: testing

workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

steps:
- name: gobuild
  image: golang:1.10.2
  commands:
  - make test
  - make static
  - sleep 30

depends_on:
- deps

---
kind: pipeline
name: building

workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

steps:
- name: gobuild
  image: golang:1.10.2
  commands:
  - make static

depends_on:
- deps

---
kind: pipeline
name: docker

steps:
- name: build
  pull: default
  image: docker:17.09.0-ce
  commands:
  - docker build -t build .
  environment:
    DOCKER_HOST: tcp://docker:2375
  when:
    event:
    - push
    - tag

depends_on:
- testing
- building

services:
- name: docker
  image: docker:18.04.0-dind
  pull: default
  ports:
  - 2375
