kind: pipeline
type: kubernetes
name: default

workspace:
  path: /go/src/github.com/UKHomeOffice/policy-admission

resources:
  request:
    cpu: 2
    memory: 8GiB
  limit:
    cpu: 4
    memory: 10GiB

steps:
- name: deps
  image: golang:1.10.2
  commands:
  - make deps

- name: test
  image: golang:1.10.2
  commands:
  - make test

- name: build
  image: golang:1.10.2
  commands:
  - make static

- name: package
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  # wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t test:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - push
    - tag
    - deployment

- name: scan-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  environment:
    IMAGE_NAME: test:${DRONE_COMMIT_SHA}
  when:
    event:
    - push
    - tag
    - deployment

- name: publish
  image: plugins/ecr
  environment:
    AWS_REGION: eu-west-2
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    repo: acp/policy-admission-ci
    registry: 670930646103.dkr.ecr.eu-west-2.amazonaws.com
    tags:
    - test-delete-me
  when:
    event:
    - push
    - tag
    - deployment

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  commands:
    - /run.sh server