kind: pipeline
type: kubernetes
name: default

workspace:
  path: /go/src/github.com/UKHomeOffice/policy-admission

steps:
- name: deps
  image: golang:1.10.2
  commands:
  - make deps

- name: test
  image: golang:1.10.2
  commands:
  - make test

- name: build
  image: golang:1.10.2
  commands:
  - make static

- name: package
  image: docker:dind
  environment:
    DOCKER_HOST: tcp://docker:2375
  commands:
  - docker build -t build .
  when:
    event:
    - push
    - tag
    - deployment

services:
- name: docker
  image: docker:dind
  environment:
    DOCKER_TLS_CERTDIR: ""
