---
kind: pipeline
name: deps

workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

steps:
- name: deps
  pull: default
  image: golang:1.10.2
  commands:
  - make deps
  when:
    event:
    - pull_request
    - push
    - tag
---
kind: pipeline
name: testing

workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

steps:
- name: gobuild
  image: golang:1.10.2
  commands:
  - make test

depends_on:
- deps
---
kind: pipeline
name: building

workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

steps:
- name: gobuild
  image: golang:1.10.2
  commands:
  - make static
- name: package
  pull: default
  image: docker:17.09.0-ce
  commands:
  - docker build -t build .
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
    - push
    - tag
    - deployment

depends_on:
- deps

services:
- name: docker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
